# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Meklarn/Desktop/EXJOBB/JonasHansson_2021VT/Vivado/ad9249_daq_custom/top_level_daq/Zynq700zc702_ad9249_daq_custom_wrapper.srcs/constrs_1/new/wrapper_cons.xdc

# Block Designs: bd/WICSC_daq/WICSC_daq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq || ORIG_REF_NAME==WICSC_daq} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_AD9249_DAQ_custom_0_0/WICSC_daq_AD9249_DAQ_custom_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_AD9249_DAQ_custom_0_0 || ORIG_REF_NAME==WICSC_daq_AD9249_DAQ_custom_0_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_processing_system7_0_0/WICSC_daq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_processing_system7_0_0 || ORIG_REF_NAME==WICSC_daq_processing_system7_0_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_xbar_0/WICSC_daq_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_xbar_0 || ORIG_REF_NAME==WICSC_daq_xbar_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_ps7_0_axi_periph_0/WICSC_daq_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_ps7_0_axi_periph_0 || ORIG_REF_NAME==WICSC_daq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_rst_ps7_0_100M_0/WICSC_daq_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_rst_ps7_0_100M_0 || ORIG_REF_NAME==WICSC_daq_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_Counter_YW_top_0_0/WICSC_daq_Counter_YW_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_Counter_YW_top_0_0 || ORIG_REF_NAME==WICSC_daq_Counter_YW_top_0_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_axi_gpio_8_0/WICSC_daq_axi_gpio_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_axi_gpio_8_0 || ORIG_REF_NAME==WICSC_daq_axi_gpio_8_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_spi3_WICSC_top_0_0/WICSC_daq_spi3_WICSC_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_spi3_WICSC_top_0_0 || ORIG_REF_NAME==WICSC_daq_spi3_WICSC_top_0_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_axi_gpio_9_0/WICSC_daq_axi_gpio_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_axi_gpio_9_0 || ORIG_REF_NAME==WICSC_daq_axi_gpio_9_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_axi_gpio_10_0/WICSC_daq_axi_gpio_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_axi_gpio_10_0 || ORIG_REF_NAME==WICSC_daq_axi_gpio_10_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_axi_gpio_11_0/WICSC_daq_axi_gpio_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_axi_gpio_11_0 || ORIG_REF_NAME==WICSC_daq_axi_gpio_11_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_xlconcat_0_0/WICSC_daq_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_xlconcat_0_0 || ORIG_REF_NAME==WICSC_daq_xlconcat_0_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_data_select_top_0_0/WICSC_daq_data_select_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_data_select_top_0_0 || ORIG_REF_NAME==WICSC_daq_data_select_top_0_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_quadrature_decoder_0_0/WICSC_daq_quadrature_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_quadrature_decoder_0_0 || ORIG_REF_NAME==WICSC_daq_quadrature_decoder_0_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_axi_gpio_12_0/WICSC_daq_axi_gpio_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_axi_gpio_12_0 || ORIG_REF_NAME==WICSC_daq_axi_gpio_12_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_xlconcat_1_0/WICSC_daq_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_xlconcat_1_0 || ORIG_REF_NAME==WICSC_daq_xlconcat_1_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_PS_Interface_TOP_0_0/WICSC_daq_PS_Interface_TOP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_PS_Interface_TOP_0_0 || ORIG_REF_NAME==WICSC_daq_PS_Interface_TOP_0_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_AD9249_DAQ_custom_1_0/WICSC_daq_AD9249_DAQ_custom_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_AD9249_DAQ_custom_1_0 || ORIG_REF_NAME==WICSC_daq_AD9249_DAQ_custom_1_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_data_select_top_1_0/WICSC_daq_data_select_top_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_data_select_top_1_0 || ORIG_REF_NAME==WICSC_daq_data_select_top_1_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_AD9249_DAQ_custom_1_1/WICSC_daq_AD9249_DAQ_custom_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_AD9249_DAQ_custom_1_1 || ORIG_REF_NAME==WICSC_daq_AD9249_DAQ_custom_1_1} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_data_select_top_1_1/WICSC_daq_data_select_top_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_data_select_top_1_1 || ORIG_REF_NAME==WICSC_daq_data_select_top_1_1} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_modulater_14bit_0_0/WICSC_daq_modulater_14bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_modulater_14bit_0_0 || ORIG_REF_NAME==WICSC_daq_modulater_14bit_0_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_clk_wiz_0_0/WICSC_daq_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_clk_wiz_0_0 || ORIG_REF_NAME==WICSC_daq_clk_wiz_0_0} -quiet] -quiet

# IP: bd/WICSC_daq/ip/WICSC_daq_auto_pc_0/WICSC_daq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WICSC_daq_auto_pc_0 || ORIG_REF_NAME==WICSC_daq_auto_pc_0} -quiet] -quiet

# XDC: bd/WICSC_daq/WICSC_daq_ooc.xdc
