# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/sampling_bd/sampling_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampling_bd || ORIG_REF_NAME==sampling_bd} -quiet] -quiet

# IP: bd/sampling_bd/ip/sampling_bd_processing_system7_0_0/sampling_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampling_bd_processing_system7_0_0 || ORIG_REF_NAME==sampling_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/sampling_bd/ip/sampling_bd_ADC_Handler_16ch_0_0/sampling_bd_ADC_Handler_16ch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampling_bd_ADC_Handler_16ch_0_0 || ORIG_REF_NAME==sampling_bd_ADC_Handler_16ch_0_0} -quiet] -quiet

# IP: bd/sampling_bd/ip/sampling_bd_axi_gpio_0_0/sampling_bd_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampling_bd_axi_gpio_0_0 || ORIG_REF_NAME==sampling_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/sampling_bd/ip/sampling_bd_axi_gpio_1_0/sampling_bd_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampling_bd_axi_gpio_1_0 || ORIG_REF_NAME==sampling_bd_axi_gpio_1_0} -quiet] -quiet

# IP: bd/sampling_bd/ip/sampling_bd_axi_gpio_3_0/sampling_bd_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampling_bd_axi_gpio_3_0 || ORIG_REF_NAME==sampling_bd_axi_gpio_3_0} -quiet] -quiet

# IP: bd/sampling_bd/ip/sampling_bd_xbar_0/sampling_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampling_bd_xbar_0 || ORIG_REF_NAME==sampling_bd_xbar_0} -quiet] -quiet

# IP: bd/sampling_bd/ip/sampling_bd_auto_pc_0/sampling_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampling_bd_auto_pc_0 || ORIG_REF_NAME==sampling_bd_auto_pc_0} -quiet] -quiet

# IP: bd/sampling_bd/ip/sampling_bd_ps7_0_axi_periph_0/sampling_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampling_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==sampling_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sampling_bd/ip/sampling_bd_rst_ps7_0_200M_0/sampling_bd_rst_ps7_0_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampling_bd_rst_ps7_0_200M_0 || ORIG_REF_NAME==sampling_bd_rst_ps7_0_200M_0} -quiet] -quiet

# XDC: bd/sampling_bd/sampling_bd_ooc.xdc
