webtalk_init -webtalk_dir C:/MPM_Zynq/quadrature_decoder_v1/quadrature_decoder_v1.sim/sim_1/behav/xsim/xsim.dir/quadrature_decoder_tb1_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 19 12:09:10 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210959682_1777518794_210650336_022" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9e9ac149-eb55-4f41-ba78-160179293bcb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "55c572147ec54f28a62a533159c551e6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "9.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14148_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3657559785 -regid "210959682_1777518794_210650336_022" -xml C:/MPM_Zynq/quadrature_decoder_v1/quadrature_decoder_v1.sim/sim_1/behav/xsim/xsim.dir/quadrature_decoder_tb1_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/MPM_Zynq/quadrature_decoder_v1/quadrature_decoder_v1.sim/sim_1/behav/xsim/xsim.dir/quadrature_decoder_tb1_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/MPM_Zynq/quadrature_decoder_v1/quadrature_decoder_v1.sim/sim_1/behav/xsim/xsim.dir/quadrature_decoder_tb1_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
