# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Pietro/Desktop/Miceli_Pietro/sampling/3_block_diagram/sampling_block_diagram.srcs/sources_1/bd/sampling_bd/ip/sampling_bd_axi_gpio_0_0/sampling_bd_axi_gpio_0_0.xci
# IP: The module: 'sampling_bd_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pietro/Desktop/Miceli_Pietro/sampling/3_block_diagram/sampling_block_diagram.srcs/sources_1/bd/sampling_bd/ip/sampling_bd_axi_gpio_0_0/sampling_bd_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sampling_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Pietro/Desktop/Miceli_Pietro/sampling/3_block_diagram/sampling_block_diagram.srcs/sources_1/bd/sampling_bd/ip/sampling_bd_axi_gpio_0_0/sampling_bd_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sampling_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Pietro/Desktop/Miceli_Pietro/sampling/3_block_diagram/sampling_block_diagram.srcs/sources_1/bd/sampling_bd/ip/sampling_bd_axi_gpio_0_0/sampling_bd_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sampling_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Pietro/Desktop/Miceli_Pietro/sampling/3_block_diagram/sampling_block_diagram.srcs/sources_1/bd/sampling_bd/ip/sampling_bd_axi_gpio_0_0/sampling_bd_axi_gpio_0_0.xci
# IP: The module: 'sampling_bd_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pietro/Desktop/Miceli_Pietro/sampling/3_block_diagram/sampling_block_diagram.srcs/sources_1/bd/sampling_bd/ip/sampling_bd_axi_gpio_0_0/sampling_bd_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sampling_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Pietro/Desktop/Miceli_Pietro/sampling/3_block_diagram/sampling_block_diagram.srcs/sources_1/bd/sampling_bd/ip/sampling_bd_axi_gpio_0_0/sampling_bd_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sampling_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Pietro/Desktop/Miceli_Pietro/sampling/3_block_diagram/sampling_block_diagram.srcs/sources_1/bd/sampling_bd/ip/sampling_bd_axi_gpio_0_0/sampling_bd_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sampling_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
