# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/pwm_bd/pwm_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_bd || ORIG_REF_NAME==pwm_bd} -quiet] -quiet

# IP: bd/pwm_bd/ip/pwm_bd_processing_system7_0_0/pwm_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_bd_processing_system7_0_0 || ORIG_REF_NAME==pwm_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/pwm_bd/ip/pwm_bd_pwm_at_0_0/pwm_bd_pwm_at_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_bd_pwm_at_0_0 || ORIG_REF_NAME==pwm_bd_pwm_at_0_0} -quiet] -quiet

# IP: bd/pwm_bd/ip/pwm_bd_T_conf_0_0/pwm_bd_T_conf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_bd_T_conf_0_0 || ORIG_REF_NAME==pwm_bd_T_conf_0_0} -quiet] -quiet

# XDC: bd/pwm_bd/pwm_bd_ooc.xdc
