# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Pietro/Desktop/Miceli_Pietro/PWM/3_block_diagram/pwm_bd.srcs/sources_1/bd/pwm_bd/ip/pwm_bd_processing_system7_0_0/pwm_bd_processing_system7_0_0.xci
# IP: The module: 'pwm_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pietro/Desktop/Miceli_Pietro/PWM/3_block_diagram/pwm_bd.srcs/sources_1/bd/pwm_bd/ip/pwm_bd_processing_system7_0_0/pwm_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Pietro/Desktop/Miceli_Pietro/PWM/3_block_diagram/pwm_bd.srcs/sources_1/bd/pwm_bd/ip/pwm_bd_processing_system7_0_0/pwm_bd_processing_system7_0_0.xci
# IP: The module: 'pwm_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Pietro/Desktop/Miceli_Pietro/PWM/3_block_diagram/pwm_bd.srcs/sources_1/bd/pwm_bd/ip/pwm_bd_processing_system7_0_0/pwm_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
